export const PRODUCTION_GOOGLE_MAPS_API_KEY = 'AIzaSyDsxzbYc_IIAeqHXkxDWJd5H2DORBd9uY0';

export const GOOGLE_MAPS_API_KEY = 'AIzaSyBH-4v8_WEj5NXXrhy4iiHMBICCYGjWEB8';

export const MAX_SELECTED_POINTS_COUNT = 12;